name: LogRite Gatekeeper

on:
  pull_request:
    branches: [ main, master, develop ]

jobs:
  log_coverage-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Gatekeeper Plugin
        run: |
          cd logrite-plugin
          go mod tidy
          go build -o gatekeeper

      - name: Debug API access
        run: |
          echo "API_URL: $API_URL"
          curl -v $API_URL || echo "Cannot reach API"
        env:
          API_URL: ${{ secrets.API_URL }}

      - name: Debug PR variables
        run: |
          echo "HEAD_REF: ${{ github.head_ref }}"
          echo "BASE_SHA: ${{ github.event.pull_request.base.sha }}"
          echo "CURRENT_SHA: ${{ github.sha }}"

      - name: Run LogRite Gatekeeper
        id: gatekeeper
        env:
          API_URL: ${{ secrets.API_URL }}
          LOG_COVERAGE_THRESHOLD: ${{ vars.LOG_COVERAGE_THRESHOLD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd logrite-plugin

          OUTPUT=$(./gatekeeper \
            --branch "${{ github.head_ref }}" \
          --base "${{ github.event.pull_request.base.sha }}" \
          --commit "${{ github.sha }}" \
          --repoURL "${{ github.server_url }}/${{ github.repository }}.git")

          echo "$OUTPUT"

          PR_LINK=$(echo "$OUTPUT" | grep pr_link | cut -d '=' -f2)
          echo "pr_link=$PR_LINK" >> $GITHUB_OUTPUT

          echo "::error file=logrite.txt,line=1::Coverage failed. Auto-fix PR created:"

          # Detect failure based on plugin exit code
          if echo "$OUTPUT" | grep -q "STATUS=fail"; then
            echo "::error file=logrite.txt,line=1::Coverage failed. Auto-fix PR created: $PR_LINK"
            exit 1
          fi

      - name: Show PR link in Checks UI
        if: failure()   # only if previous step failed
        run: |
          echo "::error::Coverage failed. Auto-fix PR created: ${{ steps.gatekeeper.outputs.pr_link }}"


      - name: Debug API access
        run: |
          echo "API_URL: $API_URL"
          curl -v $API_URL || echo "Cannot reach API"
        env:
          API_URL: ${{ secrets.API_URL }}
      
